export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const REFRESH_AUTH_TOKEN = 'REFRESH_AUTH_TOKEN';
export const TOGGLE_LOGIN_MODAL = 'TOGGLE_LOGIN_MODAL';

export const FETCH_RECIPES_START = 'FETCH_RECIPES_START';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAIL = 'FETCH_RECIPES_FAIL';

export const SET_SWITCHED_RECIPE = 'SET_SWITCHED_RECIPE';
export const SET_VIEWED_RECIPE = 'SET_VIEWED_RECIPE';
export const SET_EDITED_RECIPE = 'SET_EDITED_RECIPE';
export const TOGGLE_LIST_FILTERS = 'TOGGLE_LIST_FILTERS';

export const UPLOAD_RECIPE_START = 'UPLOAD_RECIPE_START';
export const UPLOAD_RECIPE_SUCCESS = 'UPLOAD_RECIPE_SUCCESS';
export const UPLOAD_RECIPE_FAIL = 'UPLOAD_RECIPE_FAIL';

export const DELETE_RECIPE_START = 'DELETE_RECIPE_START';
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
export const DELETE_RECIPE_FAIL = 'DELETE_RECIPE_FAIL';
